apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-rest-http-bgpc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-rest-http-bgpc
    app.kubernetes.io/part-of: nodeshift-nodejs-rest-http
  name: nodejs-rest-http-bgpc
  namespace: bgriggs-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-rest-http-bgpc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-rest-http-bgpc
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2933cd5089e321727bd07494be1aedb299412541f9cf4147c503aca773779940
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
